---
title: "Capstone Group Evaluations"
author: "Richard Maruss"
date: "05/05/2022"
output: html_document
---


## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*
Self-Evaluation




# Evaluation Areas

### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 4): __4_

Justification/Examples: Found the datasets and contributed code to evaluate and interpret the datasets.




### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 4): _4__

Justification/Examples: Respected group members ideas, also received constructive feedback from them. Asked questions and made sure we are all understanding each other.




### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 4): _4__

Justification/Examples: Wrote descriptive summaries for the Code chunks and the boxplot. Wrote code chunks and with the help of teammates were able to make the code work.




### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 4): _3__

Justification/Examples: Missed one scheduled meeting with the group due to being sick, so we had to reschedule to work together. Otherwise followed through on plans.





### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 4): __4_

Justification/Examples: Overall I believe I contributed an equal share of work.





# Total Score (out of 20): 

19




